[features]
seeds = false
skip-lint = false

[programs.localnet]
vectai_token = "DfpsT9PAeWbwwfE8EqTDqVUiCrsoHF1fogmPw42eqLPH"
vectai_oracle = "8FWpTEk2NPut6MrKXiCGVzz9ZY247fcYGdL9TEoXFqzw"
vectai_trader = "FEmf6TbtffcKVptbshZvCcg3CjQqsWodNwQhpXJff4NP"

[programs.devnet]
vectai_token = "DfpsT9PAeWbwwfE8EqTDqVUiCrsoHF1fogmPw42eqLPH"
vectai_oracle = "8FWpTEk2NPut6MrKXiCGVzz9ZY247fcYGdL9TEoXFqzw"
vectai_trader = "FEmf6TbtffcKVptbshZvCcg3CjQqsWodNwQhpXJff4NP"

[programs.mainnet]
vectai_token = "DfpsT9PAeWbwwfE8EqTDqVUiCrsoHF1fogmPw42eqLPH"
vectai_oracle = "8FWpTEk2NPut6MrKXiCGVzz9ZY247fcYGdL9TEoXFqzw"
vectai_trader = "FEmf6TbtffcKVptbshZvCcg3CjQqsWodNwQhpXJff4NP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.genesis]]
address = "VecT1111111111111111111111111111111111111"
program = "target/deploy/vectai_token.so"

[[test.genesis]]
address = "VecO2222222222222222222222222222222222222"
program = "target/deploy/vectai_oracle.so"

[[test.genesis]]
address = "VecT3333333333333333333333333333333333333"
program = "target/deploy/vectai_trader.so"

[toolchain]
anchor_version = "0.29.0"
